apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
spec:
  replicas: 5
  selector:
    matchLabels:
      type: myhttpd
  template:
    metadata:
      name: pod
      labels:
        type: myhttpd
    spec:
      containers:
      - name: container1
        image: kirandada0303723/myhttpd
        ports:
        - containerPort: 80
          name: http

---

apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    type: myhttpd
  ports:
  - port: 80
    targetPort: 80
